package termo.component;
// Generated 17-feb-2013 0:47:45 by Hibernate Tools 3.2.1.GA



/**
 * Component generated by hbm2java
 */
public class ComponentDeleted2  implements java.io.Serializable {


     private String casnumber;
     private String name;
     private String familyClass;
     private String chemFormula;
     private String unifacstructure;
     
     private Double molecularWeight;
     private Double normalBoilingPt;
     private Double idealLiqDensity;
     
     private Double criticalTemperature;
     private Double criticalPressure;
     private Double criticalVolume;
     private Double acentricFactor;
     
     private Double dipoleMoment;
     private Double radiusOfGyration;
     private Double costaldSrkAcentricity;
     private Double costaldVolume;
     private Double viscosityCoeffA;
     private Double viscosityCoeffB;
     private Double cavettHeatOfVapCoeffA;
     private Double cavettHeatOfVapCoeffB;
     private Double heatOfForm25c;
     private Double heatOfComb25c;
     private Double enthalpyBasisOffset;
     private Double rackettParameterZra;
     
     private Double prsvKappa;
     private Double kdGroupParameter;
     private Double zjEosParameter;
     private Double gsCsSolubilityParameter;
     private Double gsCsMolVolume;
     private Double gsCsAcentricity;
     private Double uniquacR;
     private Double uniquacQ;
     private Double wilsonMolarVolume;
     private Double cnSolubility;
     private Double cnMolarVolume;
     
     private Double bwrsParameterB0;
     private Double bwrsParameterA0;
     private Double bwrsParameterC0;
     private Double bwrsParameterGamma;
     private Double bwrsParameterB;
     private Double bwrsParameterA;
     private Double bwrsParameterAlpha;
     private Double bwrsParameterC;
     private Double bwrsParameterD0;
     private Double bwrsParameterD;
     private Double bwrsParameterE0;

    public ComponentDeleted2() {
    }

	
    public ComponentDeleted2(String casnumber) {
        this.casnumber = casnumber;
    }
    public ComponentDeleted2(String casnumber, String name, String familyClass, String chemFormula, String unifacstructure, Double molecularWeight, Double normalBoilingPt, Double idealLiqDensity, Double criticalTemperature, Double criticalPressure, Double criticalVolume, Double acentricFactor, Double dipoleMoment, Double radiusOfGyration, Double costaldSrkAcentricity, Double costaldVolume, Double viscosityCoeffA, Double viscosityCoeffB, Double cavettHeatOfVapCoeffA, Double cavettHeatOfVapCoeffB, Double heatOfForm25c, Double heatOfComb25c, Double enthalpyBasisOffset, Double rackettParameterZra, Double prsvKappa, Double kdGroupParameter, Double zjEosParameter, Double gsCsSolubilityParameter, Double gsCsMolVolume, Double gsCsAcentricity, Double uniquacR, Double uniquacQ, Double wilsonMolarVolume, Double cnSolubility, Double cnMolarVolume, Double bwrsParameterB0, Double bwrsParameterA0, Double bwrsParameterC0, Double bwrsParameterGamma, Double bwrsParameterB, Double bwrsParameterA, Double bwrsParameterAlpha, Double bwrsParameterC, Double bwrsParameterD0, Double bwrsParameterD, Double bwrsParameterE0) {
       this.casnumber = casnumber;
       this.name = name;
       this.familyClass = familyClass;
       this.chemFormula = chemFormula;
       this.unifacstructure = unifacstructure;
       this.molecularWeight = molecularWeight;
       this.normalBoilingPt = normalBoilingPt;
       this.idealLiqDensity = idealLiqDensity;
       this.criticalTemperature = criticalTemperature;
       this.criticalPressure = criticalPressure;
       this.criticalVolume = criticalVolume;
       this.acentricFactor = acentricFactor;
       this.dipoleMoment = dipoleMoment;
       this.radiusOfGyration = radiusOfGyration;
       this.costaldSrkAcentricity = costaldSrkAcentricity;
       this.costaldVolume = costaldVolume;
       this.viscosityCoeffA = viscosityCoeffA;
       this.viscosityCoeffB = viscosityCoeffB;
       this.cavettHeatOfVapCoeffA = cavettHeatOfVapCoeffA;
       this.cavettHeatOfVapCoeffB = cavettHeatOfVapCoeffB;
       this.heatOfForm25c = heatOfForm25c;
       this.heatOfComb25c = heatOfComb25c;
       this.enthalpyBasisOffset = enthalpyBasisOffset;
       this.rackettParameterZra = rackettParameterZra;
       this.prsvKappa = prsvKappa;
       this.kdGroupParameter = kdGroupParameter;
       this.zjEosParameter = zjEosParameter;
       this.gsCsSolubilityParameter = gsCsSolubilityParameter;
       this.gsCsMolVolume = gsCsMolVolume;
       this.gsCsAcentricity = gsCsAcentricity;
       this.uniquacR = uniquacR;
       this.uniquacQ = uniquacQ;
       this.wilsonMolarVolume = wilsonMolarVolume;
       this.cnSolubility = cnSolubility;
       this.cnMolarVolume = cnMolarVolume;
       this.bwrsParameterB0 = bwrsParameterB0;
       this.bwrsParameterA0 = bwrsParameterA0;
       this.bwrsParameterC0 = bwrsParameterC0;
       this.bwrsParameterGamma = bwrsParameterGamma;
       this.bwrsParameterB = bwrsParameterB;
       this.bwrsParameterA = bwrsParameterA;
       this.bwrsParameterAlpha = bwrsParameterAlpha;
       this.bwrsParameterC = bwrsParameterC;
       this.bwrsParameterD0 = bwrsParameterD0;
       this.bwrsParameterD = bwrsParameterD;
       this.bwrsParameterE0 = bwrsParameterE0;
    }
   
    public String getCasnumber() {
        return this.casnumber;
    }
    
    public void setCasnumber(String casnumber) {
        this.casnumber = casnumber;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFamilyClass() {
        return this.familyClass;
    }
    
    public void setFamilyClass(String familyClass) {
        this.familyClass = familyClass;
    }
    public String getChemFormula() {
        return this.chemFormula;
    }
    
    public void setChemFormula(String chemFormula) {
        this.chemFormula = chemFormula;
    }
    public String getUnifacstructure() {
        return this.unifacstructure;
    }
    
    public void setUnifacstructure(String unifacstructure) {
        this.unifacstructure = unifacstructure;
    }
    public Double getMolecularWeight() {
        return this.molecularWeight;
    }
    
    public void setMolecularWeight(Double molecularWeight) {
        this.molecularWeight = molecularWeight;
    }
    public Double getNormalBoilingPt() {
        return this.normalBoilingPt;
    }
    
    public void setNormalBoilingPt(Double normalBoilingPt) {
        this.normalBoilingPt = normalBoilingPt;
    }
    public Double getIdealLiqDensity() {
        return this.idealLiqDensity;
    }
    
    public void setIdealLiqDensity(Double idealLiqDensity) {
        this.idealLiqDensity = idealLiqDensity;
    }
    public Double getCriticalTemperature() {
        return this.criticalTemperature;
    }
    
    public void setCriticalTemperature(Double criticalTemperature) {
        this.criticalTemperature = criticalTemperature;
    }
    public Double getCriticalPressure() {
        return this.criticalPressure;
    }
    
    public void setCriticalPressure(Double criticalPressure) {
        this.criticalPressure = criticalPressure;
    }
    public Double getCriticalVolume() {
        return this.criticalVolume;
    }
    
    public void setCriticalVolume(Double criticalVolume) {
        this.criticalVolume = criticalVolume;
    }
    public Double getAcentricFactor() {
        return this.acentricFactor;
    }
    
    public void setAcentricFactor(Double acentricFactor) {
        this.acentricFactor = acentricFactor;
    }
    public Double getDipoleMoment() {
        return this.dipoleMoment;
    }
    
    public void setDipoleMoment(Double dipoleMoment) {
        this.dipoleMoment = dipoleMoment;
    }
    public Double getRadiusOfGyration() {
        return this.radiusOfGyration;
    }
    
    public void setRadiusOfGyration(Double radiusOfGyration) {
        this.radiusOfGyration = radiusOfGyration;
    }
    public Double getCostaldSrkAcentricity() {
        return this.costaldSrkAcentricity;
    }
    
    public void setCostaldSrkAcentricity(Double costaldSrkAcentricity) {
        this.costaldSrkAcentricity = costaldSrkAcentricity;
    }
    public Double getCostaldVolume() {
        return this.costaldVolume;
    }
    
    public void setCostaldVolume(Double costaldVolume) {
        this.costaldVolume = costaldVolume;
    }
    public Double getViscosityCoeffA() {
        return this.viscosityCoeffA;
    }
    
    public void setViscosityCoeffA(Double viscosityCoeffA) {
        this.viscosityCoeffA = viscosityCoeffA;
    }
    public Double getViscosityCoeffB() {
        return this.viscosityCoeffB;
    }
    
    public void setViscosityCoeffB(Double viscosityCoeffB) {
        this.viscosityCoeffB = viscosityCoeffB;
    }
    public Double getCavettHeatOfVapCoeffA() {
        return this.cavettHeatOfVapCoeffA;
    }
    
    public void setCavettHeatOfVapCoeffA(Double cavettHeatOfVapCoeffA) {
        this.cavettHeatOfVapCoeffA = cavettHeatOfVapCoeffA;
    }
    public Double getCavettHeatOfVapCoeffB() {
        return this.cavettHeatOfVapCoeffB;
    }
    
    public void setCavettHeatOfVapCoeffB(Double cavettHeatOfVapCoeffB) {
        this.cavettHeatOfVapCoeffB = cavettHeatOfVapCoeffB;
    }
    public Double getHeatOfForm25c() {
        return this.heatOfForm25c;
    }
    
    public void setHeatOfForm25c(Double heatOfForm25c) {
        this.heatOfForm25c = heatOfForm25c;
    }
    public Double getHeatOfComb25c() {
        return this.heatOfComb25c;
    }
    
    public void setHeatOfComb25c(Double heatOfComb25c) {
        this.heatOfComb25c = heatOfComb25c;
    }
    public Double getEnthalpyBasisOffset() {
        return this.enthalpyBasisOffset;
    }
    
    public void setEnthalpyBasisOffset(Double enthalpyBasisOffset) {
        this.enthalpyBasisOffset = enthalpyBasisOffset;
    }
    public Double getRackettParameterZra() {
        return this.rackettParameterZra;
    }
    
    public void setRackettParameterZra(Double rackettParameterZra) {
        this.rackettParameterZra = rackettParameterZra;
    }
    public Double getPrsvKappa() {
        return this.prsvKappa;
    }
    
    public void setPrsvKappa(Double prsvKappa) {
        this.prsvKappa = prsvKappa;
    }
    public Double getKdGroupParameter() {
        return this.kdGroupParameter;
    }
    
    public void setKdGroupParameter(Double kdGroupParameter) {
        this.kdGroupParameter = kdGroupParameter;
    }
    public Double getZjEosParameter() {
        return this.zjEosParameter;
    }
    
    public void setZjEosParameter(Double zjEosParameter) {
        this.zjEosParameter = zjEosParameter;
    }
    public Double getGsCsSolubilityParameter() {
        return this.gsCsSolubilityParameter;
    }
    
    public void setGsCsSolubilityParameter(Double gsCsSolubilityParameter) {
        this.gsCsSolubilityParameter = gsCsSolubilityParameter;
    }
    public Double getGsCsMolVolume() {
        return this.gsCsMolVolume;
    }
    
    public void setGsCsMolVolume(Double gsCsMolVolume) {
        this.gsCsMolVolume = gsCsMolVolume;
    }
    public Double getGsCsAcentricity() {
        return this.gsCsAcentricity;
    }
    
    public void setGsCsAcentricity(Double gsCsAcentricity) {
        this.gsCsAcentricity = gsCsAcentricity;
    }
    public Double getUniquacR() {
        return this.uniquacR;
    }
    
    public void setUniquacR(Double uniquacR) {
        this.uniquacR = uniquacR;
    }
    public Double getUniquacQ() {
        return this.uniquacQ;
    }
    
    public void setUniquacQ(Double uniquacQ) {
        this.uniquacQ = uniquacQ;
    }
    public Double getWilsonMolarVolume() {
        return this.wilsonMolarVolume;
    }
    
    public void setWilsonMolarVolume(Double wilsonMolarVolume) {
        this.wilsonMolarVolume = wilsonMolarVolume;
    }
    public Double getCnSolubility() {
        return this.cnSolubility;
    }
    
    public void setCnSolubility(Double cnSolubility) {
        this.cnSolubility = cnSolubility;
    }
    public Double getCnMolarVolume() {
        return this.cnMolarVolume;
    }
    
    public void setCnMolarVolume(Double cnMolarVolume) {
        this.cnMolarVolume = cnMolarVolume;
    }
    public Double getBwrsParameterB0() {
        return this.bwrsParameterB0;
    }
    
    public void setBwrsParameterB0(Double bwrsParameterB0) {
        this.bwrsParameterB0 = bwrsParameterB0;
    }
    public Double getBwrsParameterA0() {
        return this.bwrsParameterA0;
    }
    
    public void setBwrsParameterA0(Double bwrsParameterA0) {
        this.bwrsParameterA0 = bwrsParameterA0;
    }
    public Double getBwrsParameterC0() {
        return this.bwrsParameterC0;
    }
    
    public void setBwrsParameterC0(Double bwrsParameterC0) {
        this.bwrsParameterC0 = bwrsParameterC0;
    }
    public Double getBwrsParameterGamma() {
        return this.bwrsParameterGamma;
    }
    
    public void setBwrsParameterGamma(Double bwrsParameterGamma) {
        this.bwrsParameterGamma = bwrsParameterGamma;
    }
    public Double getBwrsParameterB() {
        return this.bwrsParameterB;
    }
    
    public void setBwrsParameterB(Double bwrsParameterB) {
        this.bwrsParameterB = bwrsParameterB;
    }
    public Double getBwrsParameterA() {
        return this.bwrsParameterA;
    }
    
    public void setBwrsParameterA(Double bwrsParameterA) {
        this.bwrsParameterA = bwrsParameterA;
    }
    public Double getBwrsParameterAlpha() {
        return this.bwrsParameterAlpha;
    }
    
    public void setBwrsParameterAlpha(Double bwrsParameterAlpha) {
        this.bwrsParameterAlpha = bwrsParameterAlpha;
    }
    public Double getBwrsParameterC() {
        return this.bwrsParameterC;
    }
    
    public void setBwrsParameterC(Double bwrsParameterC) {
        this.bwrsParameterC = bwrsParameterC;
    }
    public Double getBwrsParameterD0() {
        return this.bwrsParameterD0;
    }
    
    public void setBwrsParameterD0(Double bwrsParameterD0) {
        this.bwrsParameterD0 = bwrsParameterD0;
    }
    public Double getBwrsParameterD() {
        return this.bwrsParameterD;
    }
    
    public void setBwrsParameterD(Double bwrsParameterD) {
        this.bwrsParameterD = bwrsParameterD;
    }
    public Double getBwrsParameterE0() {
        return this.bwrsParameterE0;
    }
    
    public void setBwrsParameterE0(Double bwrsParameterE0) {
        this.bwrsParameterE0 = bwrsParameterE0;
    }




}


